### ISSUE TITLE
When generating server world, world made of completely random blocks. 

### ISSUE THREAD

**Issue by krissychan** [Shnupbups/extra-pieces#1]
https://pastebin.com/9v855YDd
https://images-ext-2.discordapp.net/external/4nYNQRD9Js5vKmivO0U4StvPkIP2VZFV11UN1u4nOSQ/%3Fwidth%3D400%26height%3D225/https/images-ext-1.discordapp.net/external/O3KrpiEHLmiUXQQorBUHG_e6EKZx3DUr8xfE2R77D5g/https/puu.sh/DbwXO/4d53dc73f5.jpg

**Comment by Shnupbups** [comment]
Doesn't seem to happen as of Extra Pieces 1.2.0.
