### ISSUE TITLE
Stair models are messed up although the hitbox is correct

### ISSUE THREAD

**Issue by KleinGrrmpf** [Shnupbups/extra-pieces#10]
![2019-07-10_12 35 40](https://user-images.githubusercontent.com/50833808/60963433-0d095e00-a311-11e9-9383-e1d1efe8accb.png)

The stair models are behaving weirdly when placing the stairs in a circle like in the picture above. The hitbox of the stair is correct, though, so you can stand in the middle of the four stairs.

**Comment by Shnupbups** [comment]
Haha, to be frank I'm surprised there aren't more issues with them considering I made the stair model code at 3AM. Will be fixed shortly.

**Comment by Shnupbups** [comment]
Fixed in 2.1.2
