### ISSUE TITLE
Syntax - Unsure if Issue or I'm just Stupid

### ISSUE THREAD

**Issue by Rahmiel** [Shnupbups/extra-pieces#15]
Hi, I'm back again, I know this isn't so much a code issue or bug report but I feel that in the case of a project on the scale you are trying to create, this could be deemed important. Either that or I'm just blind, I've attempted to get this "piece pack" to work for a few hours now. I'm finally breaking down and having the "OG" syntax guy to take a look at it.

One thing I would recommend is a more verbose syntax checker (I know that is probably a big ask if I'm understanding the coding required). Either way, here is the "script" I've written for this one block type.

{ 
	"magma_bricks": { 
		"base": "blockus:magma_bricks",
		"vanilla_pieces": { 
			"extrapieces:stairs": "blockus:magma_bricks_stairs",
			"extrapieces:slab": "blockus:magma_bricks_slab",
			"extrapieces:wall": "blockus:magma_bricks_wall"
		},
		"exclude": [ 
			"extrapieces:stairs",
			"extrapieces:slab",
			"extrapieces:wall"
		]
	}
}

Edit1: I tried to paste this with the "insert code" format but it messed with the formatting for some reason.

This code is in blockus.json inside the "piece pack" folder (thank you for adding that, it is a godsend for my future "diabolical" plans.

**Comment by Shnupbups** [comment]
Does your game log give an error? If so, what error is it? If not, what happens?

**Comment by Rahmiel** [comment]
Crap, I wanted to say that in the original post, but I was heading to bed. The only error I get is that blockus.json has a syntax error. No explanation beyond that. I'll get a log.

Log:  https://paste.ee/p/Bc0t5

It specifically says:
 "[22:26:27] [main/INFO]: [Extra Pieces] Loading piece pack blockus.json
[22:26:27] [main/INFO]: [Extra Pieces] SyntaxError loading piece pack blockus.json"

**Comment by Shnupbups** [comment]
Odd, the piece pack you provided works perfectly fine on my end.
![image](https://user-images.githubusercontent.com/2484721/61691447-ee728080-ad6e-11e9-80ac-9050681473de.png)

**Comment by Shnupbups** [comment]
Regardless, version 2.2.1 will print out a more in-depth log when a syntax error is found.
