### ISSUE TITLE
Connected Models for Walls

### ISSUE THREAD

**Issue by PickleWeaselPhD** [Shnupbups/extra-pieces#17]
Using Extra Pieces 1.3.0, Extra Pieces walls will connect and the models will match the vanilla implementation of walls.
**Mods:**
Extra Pieces 1.3.0
Fabric API 0.3.0+198
![2019-07-23_22 59 58](https://user-images.githubusercontent.com/35467679/61762335-a4ee5980-ad9f-11e9-9d87-d43d85e52a04.png)

Starting with Extra Pieces 2.0.0, Extra Pieces walls connect, but the models stopped matching the vanilla implementation of walls. Every wall piece uses the endcap model.
**Mods:**
Extra Pieces 2.2.0
Fabric API 0.3.0+198
![2019-07-23_22 58 52](https://user-images.githubusercontent.com/35467679/61762421-ec74e580-ad9f-11e9-8621-dacdb78dfde4.png)

**Comment by Shnupbups** [comment]
Oops! Will fix.
