### ISSUE TITLE
Layer Pieces sticky piston duplication

### ISSUE THREAD

**Issue by briansemrau** [Shnupbups/extra-pieces#21]
Using the Layer Piece, the old vanilla carpet duplication glitch works.

Using version 2.4.1.

![image](https://user-images.githubusercontent.com/6376721/61982486-d9922900-afca-11e9-9be5-9168c6f106aa.png)

Log: https://paste.ee/p/LAqd9

Note: there seem to be some other unrelated errors happening in the log, may want to look into that?

**Comment by Shnupbups** [comment]
You seem to be giving 3 issues at once here, with your title, description and note.

I will fix the first two (waterlogged by default and the duplication bug), but I'm genuinely stumped on the errors with recipes in your log.

You haven't edited the default piece pack? If you have, could you send it to me? Regardless, it shouldn't be happening.

I'll see if I can reproduce it. If not, you may have to help me further.

**Comment by briansemrau** [comment]
Oh shoot, my bad. I was writing another issue that I was going to test without other mods enabled. The issue I'm reporting is in the description.
Also, the note was separate. I probably should have looked into it for a moment rather than just posting it.

**Comment by briansemrau** [comment]
As for the error, now that you mention the default piece pack, I may need to delete it and let it regenerate. It's using the config generated in a previous version.
