### ISSUE TITLE
[2.4.2] Some fences don't connect correctly

### ISSUE THREAD

**Issue by zabi94** [Shnupbups/extra-pieces#22]
I created a pieces pack included in my mod, that add the vanilla types of piece for 3 types of wood. 2 types work fine, 1 type's fences don't connect to each other (cypress), but connect to other types of fences.
![2019-07-27_10 50 16](https://user-images.githubusercontent.com/11521878/61992308-bb750900-b05c-11e9-80bf-bcc8a3a29400.png)
![2019-07-27_10 49 01](https://user-images.githubusercontent.com/11521878/61992309-bdd76300-b05c-11e9-8e45-469d4a08efec.png)
# JSON
```
{
	"juniper_planks": {
		"base": "covens:planks_juniper",
		"include": [
			"extrapieces:slab",
			"extrapieces:stairs",
			"extrapieces:fence",
			"extrapieces:fence_gate"
		]
	},
	"cypress_planks": {
		"base": "covens:planks_cypress",
		"include": [
			"extrapieces:slab",
			"extrapieces:stairs",
			"extrapieces:fence",
			"extrapieces:fence_gate"
		]
	},
	"elder_planks": {
		"base": "covens:planks_elder",
		"include": [
			"extrapieces:slab",
			"extrapieces:stairs",
			"extrapieces:fence",
			"extrapieces:fence_gate"
		]
	}
}
```

# Environment
```
# Fabric Properties
	minecraft_version=1.14.4
	yarn_mappings=1.14.4+build.3
	loader_version=0.4.8+build.158

# Dependencies
	fabric_version=0.3.0+build.206
	modmenu_version=1.6.2-92
	rei_version=2.9.7+build.143
	extrapieces_version=2.4.2
	artifice_version=0.3.4
```

**Comment by Shnupbups** [comment]
Fences only connect to others of the same Material. Make sure all of your planks are `Material.WOOD`!

**Comment by Shnupbups** [comment]
Hmm, that's odd. Your Cypress Fences aren't being added to the fences tag. Not sure why this is happening.

Also, a side note: the convention for piece sets for wood planks is that they don't contain the word "planks". So your juniper planks set should just be called "juniper", for example. Like how, for example, vanilla stairs made of oak planks are just called "Oak Stairs".

**Comment by zabi94** [comment]
Yes, I will fix names eventually

**Comment by coderbot16** [comment]
#20 *should* fix this issue, this is likely a faulty PieceSet not being built causing all data loading to fail.

**Comment by devvoid** [comment]
Having the same issue here too, nothing is tagged so the fences/walls won't connect. While loading, I get these errors which might be related:

```
[01:18:36] [main/INFO]: [Extra Pieces] Warning: Piece Set skyroot_planks from Piece Pack extrapieces.luminiferous_uplands.json was not built!
[01:18:36] [main/INFO]: [Extra Pieces] Warning: Piece Set uplander_stone from Piece Pack extrapieces.luminiferous_uplands.json was not built!
```

Here's the piece pack:

```json
{
  "version": "1.0.0",
  "sets": {
    "skyroot_planks": {
      "base": "$modid:skyroot_planks",
      "exclude": [
        "extrapieces:wall"
      ]
    },
    "uplander_stone": {
      "base": "$modid:uplander_stone",
      "exclude": [
        "extrapieces:fence",
        "extrapieces:fence_gate"
      ]
    }
  }
}
```

**Comment by devvoid** [comment]
After doing some more experimentation, it seems that piece packs from mods aren't built at all; not only are blocks not tagged, but no recipes are loaded at all (for the stonecutter or the crafting table). If I had to take a shot in the dark, `PieceSet.Builder.build()` seems like it's not being called.

**Comment by coderbot16** [comment]
Are *all* modded piece packs broken or are only the ones involving skyroot planks or uplander stone? I'm gussing that the `$modid` part is invalid, the actual modid needs to be there (probably `luminiferous_uplands`)

**Comment by devvoid** [comment]
I haven't tried out any other mods yet, but the default pack has all its items properly tagged. Using the mod id instead of `$modid` doesn't change anything.
