### ISSUE TITLE
Сrafting fences, fence gates and layers is not possible

### ISSUE THREAD

**Issue by grn-kunnnn** [Shnupbups/extra-pieces#29]
I have some ideas on how this might look. They are presented below:
![fence](https://user-images.githubusercontent.com/54494585/63646896-6e02bf00-c722-11e9-825c-53778c32c492.png)
![fence-gate](https://user-images.githubusercontent.com/54494585/63646897-6e9b5580-c722-11e9-8b46-6df239f9ae3a.png)
![hb-to-layers](https://user-images.githubusercontent.com/54494585/63646898-6e9b5580-c722-11e9-9bc9-714c219b229f.png)

**Comment by grn-kunnnn** [comment]
Please, add it

**Comment by Shnupbups** [comment]
Added in 2.6.0

**Comment by grn-kunnnn** [comment]
Thank you!!!!
