### ISSUE TITLE
No drops

### ISSUE THREAD

**Issue by trollsdottir** [Shnupbups/extra-pieces#3]
After updating to newest fabric API blocks don't drop (I tried mining terracotta slab). As I have the same problem with blocks from at least two other mods (Epicurean and Cotton Resources), I thought I give the info to the coders.

**Comment by Shnupbups** [comment]
I think this might be an issue with the API itself rather than with Extra Pieces, Epicurean Gastronomy or Cotton Resources. Is it still happening with the latest API version?

**Comment by trollsdottir** [comment]
Yes It has been hapenning in .165, 166, .167. And I checked other mod (Blockus), works the same. I'm gonna write API author.

**Comment by trollsdottir** [comment]
[1.14.1] Fabric API 0.3.0-pre build 157a works just fine, but not later version

https://github.com/FabricMC/fabric/issues/210 here are more people who actually know programming (unlike me) talking about it.

EDIT: Fabric API programmers found where the problem stems from, so it is not an issue with this mod.
