### ISSUE TITLE
Crafting table gives Basalt fence recipe after the crafting grid is emptied

### ISSUE THREAD

**Issue by Snekytits** [Shnupbups/extra-pieces#31]
Placing any item in the crafting grid and emptying it gives you an option to craft 6 basalt

Placing any items even with no recipe
![craft grid](https://user-images.githubusercontent.com/54674540/63946820-5facfe00-caa8-11e9-972a-7019bbb223fd.png)

Grid is emptied
![2019-08-29_15 11 40](https://user-images.githubusercontent.com/54674540/63946856-6dfb1a00-caa8-11e9-83ea-6c1e65dc85dc.png)

The item can be crafted and used
![2019-08-29_15 11 47](https://user-images.githubusercontent.com/54674540/63946870-76535500-caa8-11e9-902a-615e78a1c39f.png)

**Comment by Shnupbups** [comment]
Could you update to 2.7.0, run the game and if it's still happening (or if there *isn't any recipe* for that piece now) could you go into your config folder, find `extrapieces/config.json` and set debugOutput and moreDebugOutput to true?

**Comment by Snekytits** [comment]
Alright tested out the new version. The crafting bug is gone. The Chiseled basalt bricks siding is still craftable.
Heres the log for it:
https://paste.ee/p/M5HQo

**Comment by Shnupbups** [comment]
Hang on, so the bug is gone *and* the siding has its regular recipe? Huh. Weird. Didn't expect that.

Anyway, I guess that means this is fixed?
