### ISSUE TITLE
[1.16.1] Crash with Adorn

### ISSUE THREAD

**Issue by cybercat5555** [Shnupbups/extra-pieces#44]
While the 1.16.1 update is very much appreciated, it crashes with Adorn 1.9.1 for Fabric 1.16.1. Removing Adorn fixes the crash.

[crash-2020-08-01_12.36.58-client.txt](https://github.com/Shnupbups/extra-pieces/files/5010931/crash-2020-08-01_12.36.58-client.txt)

**Comment by Shnupbups** [comment]
This is a problem on Adorn's end. @Juuxel needs to fix this!

**Comment by Juuxel** [comment]
Yeah, this is a duplicate of Juuxel/Adorn#92.
