### ISSUE TITLE
Visual Problem when running with shaders.

### ISSUE THREAD

**Issue by echo451** [Shnupbups/extra-pieces#6]
When I upgraded from the 1.3.0 version to the 2.0.0 version I encounter problems when running Sildurs Vibrant Shaders, V1,22 Lite version. 

This shader worked fine with the older version. 

When using the new version this problem appears when using the internal shader as well.

This first picture is with the old version. Shaders are fine

![2019-07-05_14 17 02](https://user-images.githubusercontent.com/52583998/60745599-fc7f6f00-9f2f-11e9-8307-cc69b0061034.png)

The next picture is with the latest.

![2019-07-05_14 19 21](https://user-images.githubusercontent.com/52583998/60745632-26389600-9f30-11e9-84b5-0fb900addc43.png)

The resource pack is Monsterley_128_1_190623

Let me know if you need more information or someone to test out a fix.

I don't run with the shaders normally so it an accident that I found this.

**Comment by Shnupbups** [comment]
This is likely a problem with JMX or its dependencies. JMX is bundled with Extra Pieces as it uses it for block model generation, but it is not developed by me. Please report it [here](https://github.com/grondag/json-model-extensions/issues).

**Comment by echo451** [comment]
A reported a bug as suggested. Linked back to this report. Was there a library version change between the two release.

This is a great mod. Good work. Grass blocks that are tiled on more than one face. I can't live without it now. Landscapers delight.

**Comment by Shnupbups** [comment]
Extra Pieces versions prior to 2.0 did not use JMX, nor any libraries other than Fabric API. Extra Pieces 2.1 will likely ditch JMX in favour of other methods, thus essentially fixing this issue as far as Extra Pieces is concerned.

**Comment by Shnupbups** [comment]
Resolved by #8
