### ISSUE TITLE
Vector placing issue with 2.0.0 

### ISSUE THREAD

**Issue by Dragonracer1973** [Shnupbups/extra-pieces#7]
Not sure if its because I transfered the world save file over from 1.14.2, or if it may be another mod interfering  (accurate block placement comes to mind) but I cannot get the long face of the corner to face the right side of a block
![2019-07-07_07 23 49](https://user-images.githubusercontent.com/50302305/60768397-3748ea80-a089-11e9-971a-c29d75922160.png) essentially I want it to touch the window pane. 

![2019-07-07_07 32 46](https://user-images.githubusercontent.com/50302305/60768426-7119f100-a089-11e9-8c6a-67aac2ab87c7.png) this is a pic from my 1.14.2 instance build. 

FYI I am in the Fabric discord if you want to hit me up there. 
Love the mod btw

**Comment by Shnupbups** [comment]
Corner placement is a known issue in 2.0. It will (attempt to) be fixed in 2.1.

**Comment by Shnupbups** [comment]
Resolved by #8
