### ISSUE TITLE
Issues placing sidings

### ISSUE THREAD

**Issue by calloatti** [Shnupbups/extra-pieces#9]
Just some issues when placing sidings
extrapieces-2.1.0
Default config

When I aim here:
![2019-07-09_17 24 54](https://user-images.githubusercontent.com/12817862/60920667-1fcb5680-a26f-11e9-82a1-53c1d7393d0f.png)
I expect this:
![2019-07-09_17 25 09](https://user-images.githubusercontent.com/12817862/60920690-2a85eb80-a26f-11e9-8e3f-b46dea560ec7.png)
Instead I get this:
![2019-07-09_17 25 43](https://user-images.githubusercontent.com/12817862/60920704-340f5380-a26f-11e9-99e3-4aeb55f2779a.png)

---

When I aim here from this position:
![2019-07-09_17 26 51](https://user-images.githubusercontent.com/12817862/60920889-9e27f880-a26f-11e9-9d35-381fef250e40.png)
I expect this:
![2019-07-09_17 27 14](https://user-images.githubusercontent.com/12817862/60920900-a6803380-a26f-11e9-8ae9-4f7b394ffbd5.png)
Instead I get this:
![2019-07-09_17 27 04](https://user-images.githubusercontent.com/12817862/60920912-ad0eab00-a26f-11e9-9be4-3fc9270ca458.png)

**Comment by Shnupbups** [comment]
Thanks for providing screenshots! I'll attempt to fix Siding placement again next update.

**Comment by Shnupbups** [comment]
Should be fixed as of 2.1.1
